#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  6 12:33:05 2021

@author: DANI
"""

# This program mimics the minimal functions of a lottery system

import random

class winning_number: 
    lottery= random.sample(range(0,5),1)
    print(lottery)
    winning_number = [4]
    if lottery == winning_number:
        print("Congratulations! You are the winner!")