#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 22 16:21:07 2021

@author: DANI
@title: Classifying handwritten MNIST Handwritten Digit Recognition in PyTorch with digits from the MNIST dataset

"""

# This convolutional neural network in PyTorch can be trained to recognize handwritten digits using the MNIST dataset
  ## The MNIST dataset is considered the hello world of image recognition

#Build the Environment
import torch
import torchvision

#Prepare the dataset
n_epochs = 3 #Defines the # of times that will loop over the dataset
batch_size_train = 64
batch_size_test = 1000
learning_rate = 0.01  #Defines the hyperparameters
momentum = 0.5 #Defines the hyperparameters
log_interval = 10
random_seed = 1 #Enables random number generation
torch.backends.cudnn.enabled = False #Disables nondeterministic algorithms
torch.manual_seed(random_seed)

#Load the data
train_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/Users/DANI/Desktop', train=True, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_train, shuffle=True)

test_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('/Users/DANI/Desktop', train=False, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_test, shuffle=True)

#Enable Data Loader options
examples = enumerate(test_loader)
batch_idx, (example_data, example_targets) = next(examples)

#See what one test data batch consists of
example_data.shape

#Set up the Environment
import matplotlib.pyplot as plt

#Plot the data batches using matplotlib
fig = plt.figure()
for i in range(6):
  plt.subplot(2,3,i+1)
  plt.tight_layout()
  plt.imshow(example_data[i][0], cmap='gray', interpolation='none')
  plt.title("Ground Truth: {}".format(example_targets[i]))
  plt.xticks([])
  plt.yticks([])
  
#Set up these environments to produce readable code
import torch.nn as nn #Defines the trainable parameters
import torch.nn.functional as F #Defines the functional parameters
import torch.optim as optim

#Build a network  by creating a new class for the desired network
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x)  

#Initialize the network and the optimizer
network = Net()
optimizer = optim.SGD(network.parameters(), lr=learning_rate,
                      momentum=momentum)

#Keep track of the progress with some printouts
train_losses = [] #Creates a list for saving training losses
train_counter = []
test_losses = [] #Creates a list for saving testing losses
test_counter = [i*len(train_loader.dataset) for i in range(n_epochs + 1)] #Displays the # of training examples the network has seen during training

#Train the model
def train(epoch):
  network.train()
  for batch_idx, (data, target) in enumerate(train_loader):
    optimizer.zero_grad()
    output = network(data)
    loss = F.nll_loss(output, target)
    loss.backward()
    optimizer.step()
    if batch_idx % log_interval == 0:
      print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
        epoch, batch_idx * len(data), len(train_loader.dataset),
        100. * batch_idx / len(train_loader), loss.item()))
      train_losses.append(loss.item())
      train_counter.append(
        (batch_idx*64) + ((epoch-1)*len(train_loader.dataset)))
      torch.save(network.state_dict(), '/results/model.pth')
      torch.save(optimizer.state_dict(), '/results/optimizer.pth')

#Add the test loss and keep track of correctly classified digits to compute the network's accuracy of the network
def test():
  network.eval()
  test_loss = 0
  correct = 0
  with torch.no_grad():
    for data, target in test_loader:
      output = network(data)
      test_loss += F.nll_loss(output, target, size_average=False).item()
      pred = output.data.max(1, keepdim=True)[1]
      correct += pred.eq(target.data.view_as(pred)).sum()
  test_loss /= len(test_loader.dataset)
  test_losses.append(test_loss)
  print('\nTest set: Avg. loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
    test_loss, correct, len(test_loader.dataset),
    100. * correct / len(test_loader.dataset)))

#Run the training
#Add a test() call before we loop over n_epochs to evaluate our model with randomly initialized parameters
test()
for epoch in range(1, n_epochs + 1):
  train(epoch)
  test()
  
#Plot the training curve
fig = plt.figure()
plt.plot(train_counter, train_losses, color='blue')
plt.scatter(test_counter, test_losses, color='red')
plt.legend(['Train Loss', 'Test Loss'], loc='upper right')
plt.xlabel('number of training examples seen')
plt.ylabel('negative log likelihood loss')
fig

#Continue comparing the model's output
with torch.no_grad():
  output = network(example_data)
  
fig = plt.figure()
for i in range(6):
  plt.subplot(2,3,i+1)
  plt.tight_layout()
  plt.imshow(example_data[i][0], cmap='gray', interpolation='none')
  plt.title("Prediction: {}".format(
    output.data.max(1, keepdim=True)[1][i].item()))
  plt.xticks([])
  plt.yticks([])
fig

#Initialize a new set of network and optimizers
continued_network = Net()
continued_optimizer = optim.SGD(network.parameters(), lr=learning_rate,
                                momentum=momentum)

#Load the internal state of the network and optimizer when we last saved them
network_state_dict = torch.load()
continued_network.load_state_dict(network_state_dict)

optimizer_state_dict = torch.load()
continued_optimizer.load_state_dict(optimizer_state_dict)

#Keep track of the loss values
for i in range(4,9):
  test_counter.append(i*len(train_loader.dataset))
  train(i)
  test()

#Inspect the training progress
fig = plt.figure()
plt.plot(train_counter, train_losses, color='blue')
plt.scatter(test_counter, test_losses, color='red')
plt.legend(['Train Loss', 'Test Loss'], loc='upper right')
plt.xlabel('number of training examples seen')
plt.ylabel('negative log likelihood loss')
fig

