#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 13 15:38:52 2021

@author: DANI
"""
#Generate a strong password
def strong_password():
#Ask someone for their name and DOB
    name = 'Danielle'
    DOB = '1998'
#String manipulation
    name = name[::-1]
    name = name.replace('e','ut')  
    DOB = DOB.replace('9','5')
    DOB = DOB[:1] + '!$' + DOB[1:]
    print(str(name) + str(DOB))

#Print a strong password
strong_password()

#Generate an intermediate password
def intermediate_password():
#Ask someone for their name and DOB
    name = 'Danielle'
    DOB = '1998'
#String manipulation
    name = name.upper()
    DOB = DOB[::-1]
    DOB = DOB[:1] + '_' + DOB[1:]
    print(str(name) + str(DOB))

#Print an intermediate password
intermediate_password()

#Generate a weak password
def weak_password():
#Ask someone for their name and DOB
    name = 'Danielle'
    DOB = '1998'
#String manipulation
    name = name.lower()
    name = name.replace('a', 'p')
    DOB = " ".join(DOB.split('8'))
    print(str(name) + str(DOB))

#Print a weak password
weak_password()

