#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: DANI
@title: Programming exercises
"""

def BMI_calculator():
#Introduces user to the BMI calculator
    print('BMI Calculator:\n')
#Gets input from the user and assigning it to user
    height = float(input("Enter height in meters:\n"))
    weight = float(input("Enter weight in kg:\n"))
#Calculates the user's BMI
    BMI = weight/(height**2) 
    print("Your BMI is: {0} and you are: ".format(BMI), end='')
#Factors the health conditions
    if (BMI < 16):
        print("Severely underweight")
    elif (BMI >= 16 and BMI < 18.5):
        print("Underweight")
    elif (BMI >= 18.5 and BMI < 25):
        print("Healthy")
    elif (BMI >= 25 and BMI < 30):
        print("Overweight")
    elif (BMI >=30):
        print("Severely overweight")
   
BMI_calculator()
    
def number_calculator():
    x = int(input("Enter first number:\n"))
    y = int(input("Enter second number:\n"))
#Calculates the sum of numbers in a list using a for loop 
    for x in range(0,10000): 
#Uses the sum function
        sum=x+y
        average=sum/2
        print("Sum of the given two numbers is:", sum)
        print("Average of the given numbers is:", average)
        break

number_calculator()

def odd_calculator():
   i = 2
#Uses a while loop
   while i <10:
       if i %2 != 0:
           print("Odd number:")
#Prints all odd numbers below 10
           print(i)
       i = i+1
       
odd_calculator()

